### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Bhum-ika** [Vin205/Enyanjyoti#1]
Kindly include these topics in the README file:
Project Title
Project Description
Guidelines for contributing to the project
Kindly assign this issue to me with the gssoc-extd and hactoberfest tag so I can start working on it

**Comment by Muskan-bhatt249** [comment]
@Bhum-ika Please assign this to me if this issue is a part if GSSoC-Ext and please add the tags

**Comment by Bhum-ika** [comment]
I am also a contributor, not a project admin @Muskan-bhatt249

**Comment by skmirajulislam** [comment]
@Bhum-ika you have assigned to do!

**Comment by skmirajulislam** [comment]
unfortunately im closing this issue already someone done this #24
