### ISSUE TITLE
Enhancing the UI

### ISSUE THREAD

**Issue by RIYA-YADAV-19** [Vin205/Enyanjyoti#10]
Enhancing the UI and making it more interactive and modern so that user gets more interested in the website.

**Comment by skmirajulislam** [comment]
@RIYA-YADAV-19 is assigned for this issue!

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!

**Comment by RIYA-YADAV-19** [comment]
> @RIYA-YADAV-19 is assigned for this issue!

Thank you, I will do it surely
