### ISSUE TITLE
AI Chatbot Integration 

### ISSUE THREAD

**Issue by linga-007** [Vin205/Enyanjyoti#100]
i would like to add chatbot facility to this project . Kindly asssign me this issue . 
Request you to add gssoc extd , hactoberfest labels

**Comment by skmirajulislam** [comment]
@linga-007 interesting.

**Comment by skmirajulislam** [comment]
Make sure it will be able to meet the project domain and give a clear reply to all users !

**Comment by amanver45** [comment]
@skmirajulislam @linga-007 can i work on this issue if you  @linga-007  are not intersted in this issue

**Comment by skmirajulislam** [comment]
@linga-007 assigned!
