### ISSUE TITLE
(Enhancement) (Level1) #Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [Vin205/Enyanjyoti#104]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by skmirajulislam** [comment]
@KiranBaliga assigned!

**Comment by KiranBaliga** [comment]
@skmirajulislam Please review the PR and action accordingly.

Please add the above labels to the linked PR as well.

Thank you for the opportunity.
