### ISSUE TITLE
The readme.file is not maintained properly

### ISSUE THREAD

**Issue by ananyag309** [Vin205/Enyanjyoti#106]
add featured in table 
![featured in](https://github.com/user-attachments/assets/8cf3c981-de26-4cb0-8c1e-03b1317cd337)

also the contributor should be placed at the end of the file

**Comment by skmirajulislam** [comment]
@ananyag309 assigned!

**Comment by skmirajulislam** [comment]
@ananyag309 thanks for your contribution 🎇!
