### ISSUE TITLE
fix the responsiveness of signup page and login page 

### ISSUE THREAD

**Issue by AyushSharma72** [Vin205/Enyanjyoti#109]
![image](https://github.com/user-attachments/assets/40593722-0c1c-4842-b482-be8aea596096)

![image](https://github.com/user-attachments/assets/7154f0c1-704e-4366-b169-0ef1fd9daa29)

i want to fix the responsive ness of the signup page and login page please assign this issue to me @Vin205

**Comment by skmirajulislam** [comment]
@AyushSharma72 RESOLVED THIS ISSUE
