### ISSUE TITLE
Missing Description

### ISSUE THREAD

**Issue by aditiverma-21** [Vin205/Enyanjyoti#11]
Adding Description about the project in about section

**Comment by skmirajulislam** [comment]
@aditiverma-21 Sure! I’ll assign you the task of adding a description about the project in the About section. However, please check with the admin for more relevant details before proceeding. Let me know if you need any assistance!

**Comment by aditiverma-21** [comment]
Yaa sure I'll write the description. where should I have to add that if I create a fork?

**Comment by skmirajulislam** [comment]
@aditiverma-21 do you want to add a new section on website or in Documentation in readme.md ?

**Comment by aditiverma-21** [comment]
@skmirajulislam in readme.md because there is no exact description of the website and its features

**Comment by skmirajulislam** [comment]
@aditiverma-21 okey then change it , well

**Comment by aditiverma-21** [comment]
Yes sure.

**Comment by skmirajulislam** [comment]
@aditiverma-21  Please ensure that someone has already submitted a pull request for this. If there isn't one, it's important to provide better visibility on the existing PR. Otherwise, there won't be any points awarded. please view this PR #7
