### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by PankajKumardev** [Vin205/Enyanjyoti#110]
I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

[x ] I am contributing under GSSoC-ext
[x ] I am contributing under hacktoberfest

**Comment by PankajKumardev** [comment]
done , the docker work , pulled the updated code

**Comment by skmirajulislam** [comment]
@PankajKumardev solved this issue!
