### ISSUE TITLE
Add GitHub Workflow for Auto-Closing Similar Issue Requests and autolabeler

### ISSUE THREAD

**Issue by shubhagarwal1** [Vin205/Enyanjyoti#112]
Implement a GitHub workflow that automatically detects and closes duplicate or similar issue requests. The workflow should:

Utilize a bot or script to compare new issues against existing ones.
Automatically flag or close issues with matching titles, descriptions, or keywords.
Provide a comment linking the user to the original issue for reference.
Ensure the workflow runs on issue creation to streamline project management.

Hey @Vin205 please assign this task to me.

**Comment by skmirajulislam** [comment]
@shubhagarwal1 assigned!
