### ISSUE TITLE
# Bug Forgot password is not working and it is redirecting to a different page

### ISSUE THREAD

**Issue by praveenarjun** [Vin205/Enyanjyoti#114]
:red_circle: Title: Bug: Forgot Password Not Working and Redirecting to a Different Page
:red_circle: Aim: To fix the issue with the "Forgot Password" functionality that is not working and is redirecting users to an incorrect page.
:red_circle: Brief Explanation: The "Forgot Password" feature on the Enyanjyoti platform is currently malfunctioning. When users attempt to reset their passwords, they are redirected to an unexpected page rather than receiving the reset instructions. This bug needs to be investigated and resolved to ensure users can reset their passwords successfully.
Steps to Reproduce:

    Navigate to the login page.
    Click on the "Forgot Password" link.
    Enter the registered email address.
    Observe the redirection to an incorrect page.

Expected Behavior:

    Users should receive an email with password reset instructions.
    Users should not be redirected to an incorrect page.

Actual Behavior:

    Users are redirected to an unexpected page.
    No email with password reset instructions is received.

Screenshots 📷 
after clicking forgot password it redirecting to this page
![Screenshot 2024-10-08 at 1 35 53 AM](https://github.com/user-attachments/assets/92c7c77d-189f-46f6-9701-f22cc501262d)

:white_check_mark: To be Mentioned while taking the issue:

    Full name: Sree Praveen challa
    What is your participant role?  GSSOC,hackbefest

Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by skmirajulislam** [comment]
@praveenarjun assigned!
