### ISSUE TITLE
New Favicon Design

### ISSUE THREAD

**Issue by codingkatty** [Vin205/Enyanjyoti#115]
Hi there, right now, I realized that the favicon is quite squeezed version of the logo, hence I suggest a new favicon to be made, and the main icon to be in svg. Here's a pic of the favicon I made based on the current logo, I can edit it more :)

![favicon](https://github.com/user-attachments/assets/d3e4974d-6f7a-45d8-8c9a-5ca8224bca4e)
![comparison](https://github.com/user-attachments/assets/c67bfe8e-29f5-435a-a512-985351765d3a)

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.
I hope that it can be considered. Thanks!

**Comment by skmirajulislam** [comment]
@codingkatty assigned!

**Comment by skmirajulislam** [comment]
@codingkatty resolved!
