### ISSUE TITLE
Enhancing Ui of contactUs page

### ISSUE THREAD

**Issue by Bhum-ika** [Vin205/Enyanjyoti#116]
![image](https://github.com/user-attachments/assets/5f8cee83-3618-48a3-ab31-f4a8c92921ea)
The Ui is very basic. I can add some great properties to make it look attractive.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by MohitGoyal09** [comment]
Pls assign me this issue

**Comment by skmirajulislam** [comment]
@Bhum-ika assigned!

**Comment by skmirajulislam** [comment]
@Bhum-ika resolved!

**Comment by Bhum-ika** [comment]
@skmirajulislam I hope you have upgraded the level
