### ISSUE TITLE
 Incorrect Naming of Platform - "Nyanjyoti" Should be "Gyanjyoti"

### ISSUE THREAD

**Issue by Iamanujosh** [Vin205/Enyanjyoti#117]
The platform is currently named "Nyanjyoti," which appears to be a misspelling or misrepresentation of the intended name. The correct term should be "Gyanjyoti," where "Gyan" (ज्ञान) means knowledge in Sanskrit and aligns with the purpose of the platform—promoting education and learning. The current name may cause confusion and diminish the platform's credibility.
![image](https://github.com/user-attachments/assets/4ca08d39-04f2-4e10-86c0-8e272d3ae825)

**Impact:**

Misinterpretation of the platform’s core values and mission.
Potential confusion among users, particularly those familiar with the word "Gyan" in educational contexts.
The platform may not resonate well with users, as "Gyanjyoti" carries a more meaningful and culturally relevant message.

**Proposed Solution:**

Rename the platform to "Gyanjyoti" to reflect the intended focus on education and knowledge.
Update branding, logos, URLs, and all marketing materials to reflect the correct name.
Communicate the change clearly to users to avoid any confusion during the transition.

**Comment by skmirajulislam** [comment]
@Iamanujosh, the platform name cannot be changed as it has already been listed under Hacktoberfest and GSSOC with the same name. Additionally, PA @Vin205 has rejected the request. We apologize for the inconvenience and encourage you to contribute to other functionalities instead.
