### ISSUE TITLE
Issue: FAQ Section Expands on Hover

### ISSUE THREAD

**Issue by idk-mr4tyunjay** [Vin205/Enyanjyoti#119]
**Problem:**
The FAQ section currently requires users to click on each question to reveal the corresponding answer. However, it would improve the user experience if the FAQ section opened when a user hovers over a question and closed when the hover is removed. This would provide a more dynamic and responsive interaction model.

**Reproduction Steps:**
1. Navigate to the FAQ section of the website.
2. Hover over any question in the FAQ list.
3. Currently, the question remains static until clicked. 

**Expected Behavior:**
- Upon hovering over a question, the corresponding answer should automatically expand.
- When the user moves the cursor away, the answer should close automatically.

**Actual Behavior:**
- At the moment, the FAQ requires a click to expand and close.

**Suggested Fix:**
Implement hover-based functionality for FAQ expansion and collapse. Ensure that the transition is smooth and does not affect the overall user experience negatively, especially on touch devices.

**Impact:**
This change would streamline interaction with the FAQ section, making it more intuitive and responsive for desktop users.

@Vin205 kindly add proper labels and assign this issue to me, thank you

![image](https://github.com/user-attachments/assets/515ce50a-54b8-4edc-9c80-41cd48e28599)

**Comment by skmirajulislam** [comment]
@idk-mr4tyunjay assigned!
