### ISSUE TITLE
Guildlines

### ISSUE THREAD

**Issue by aditiverma-21** [Vin205/Enyanjyoti#12]
Deployment guidelines for the project

**Comment by skmirajulislam** [comment]
@aditiverma-21 sorry for that this should be mentioned by **project admin @Vin205**,  No problem! Please consider proposing a different feature or enhancement for the project. Feel free to share your ideas, and I can help you assign the next task. Looking forward to your contribution!

**Comment by aditiverma-21** [comment]
Yes sure thank you.
