### ISSUE TITLE
FIXING THE NAV BAR 

### ISSUE THREAD

**Issue by RAJIV81205** [Vin205/Enyanjyoti#120]
I WILL FIX THE NAV BAR MAKE IT ALWAYS VISIBLE ON THE PAGE AND ALSO MAKING IT TRANSPARENT FOR A BETTER UI EXPERIENCE 
![image](https://github.com/user-attachments/assets/6705c36a-c760-453d-bc9b-478f82699de1)
PLEASE ASSIGN ME TO FIX IT

**Comment by skmirajulislam** [comment]
@RAJIV81205 explain it by demonstrating your issue through screenshot or img!

**Comment by RAJIV81205** [comment]
The header looks very simple . I will make it translucent on all the pages and also make it responsive on all the pages and and also fix the position

**Comment by skmirajulislam** [comment]
> The header looks very simple . I will make it translucent on all the pages and also make it responsive on all the pages and and also fix the position

explain it by demonstrating your issue through screenshot or img!

**Comment by maxwithbug** [comment]
UI, logo, hover, shadow, and alignment must be fixed. It should always visible on the screen for easy accessibility on things . The website also needs a dark theme and toggle button on the navbar. I can do that, can I work on this? Please give it a review one more thing can you assign me this topic

**Comment by skmirajulislam** [comment]
@maxwithbug Assigned for this particular issue under hacktoberfest & GSSoC!

**Comment by skmirajulislam** [comment]
@maxwithbug resolve it earlier within 24 hours it will be closed because of redeployment!
