### ISSUE TITLE
No Loan option in toggle button

### ISSUE THREAD

**Issue by sayanp607** [Vin205/Enyanjyoti#123]
![Screenshot 2024-10-08 104816](https://github.com/user-attachments/assets/2293ecb3-c35a-40b9-9b9e-9e79df510d95)
Please assign this issue to me, I will fix it properly for sure.

**Comment by skmirajulislam** [comment]
@sayanp607 assigned!

**Comment by skmirajulislam** [comment]
@sayanp607 resolved this!
