### ISSUE TITLE
Proposal to Implement Backend Functionality

### ISSUE THREAD

**Issue by tejasbenibagde** [Vin205/Enyanjyoti#125]
Hi there!

I noticed that the `backend` folder is currently empty. I would like to propose working on this folder to create a complete server that responds to API requests. 

Could you please share any preferred programming language for this implementation?

### I have two options 

1. `Typescript`
2. `Javascript`

Looking forward to your guidance!

Thank you!

**Comment by skmirajulislam** [comment]
resolved!
