### ISSUE TITLE
FIX THE NAVBAR add Hamburger 

### ISSUE THREAD

**Issue by sahhoArjun097** [Vin205/Enyanjyoti#13]
I can fix the UI of the navbar and add hamburger on the navbar .

![image](https://github.com/user-attachments/assets/e7c0a7d7-7c00-4fa3-bd7b-baee18f6f1b8)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

**Comment by skmirajulislam** [comment]
@sahhoArjun097 You’re assigned to fix the UI of the navbar and add a hamburger menu. Please make sure the navbar is responsive and user-friendly. Submit a pull request when you're done. Let me know if you need any guidance!

**Comment by sahhoArjun097** [comment]
ok

**Comment by skmirajulislam** [comment]
#35 resolved and accepted
