### ISSUE TITLE
To update social icon 

### ISSUE THREAD

**Issue by Antima2004** [Vin205/Enyanjyoti#135]
In the footer section there are social media icon but the twitter logo is not updated 
Here's the image of it:
![Screenshot 2024-10-08 11 58 49 PM](https://github.com/user-attachments/assets/68bf5256-f528-4517-ba29-42af5339b528)

Please assign this to me and also add label

**Comment by skmirajulislam** [comment]
@Antima2004 assigned make sure someone already working on it, please raise your PR earlier!

**Comment by skmirajulislam** [comment]
@HarshadaGirase resolved this issue!
