### ISSUE TITLE
ADD FOOTER SECTION TO THE PAGE  

### ISSUE THREAD

**Issue by sahhoArjun097** [Vin205/Enyanjyoti#14]
I CAN add footer section to the page that will be responsive . 

![image](https://github.com/user-attachments/assets/ff327d4d-cf38-4f76-8107-4cfbae66eb50)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant  and lvl.

**Comment by skmirajulislam** [comment]
@sahhoArjun097 Great! You’re assigned to add a responsive footer section to the page. Points will be awarded upon review & evolution.

**Comment by skmirajulislam** [comment]
issue resolved!
