### ISSUE TITLE
Enhancing consistency of Skill Card on Home page

### ISSUE THREAD

**Issue by iamsaura8h** [Vin205/Enyanjyoti#145]
hey @Vin205 , 
as a ui/ux designer it feels to see inconsistency in a web app and it  happens that there's one in e-nyanjoti's home page.
refer to screenshot below : 

<img width="960" alt="is13" src="https://github.com/user-attachments/assets/f873016b-96fd-4bc5-b6c4-ab7ca8c6c782">
 
 as you can see the placement of buttons are so inconsistent, please allow me to fix this hence assign me this issue.
 don't forget to add `gssoc-ext` and `hactoberfest-accepted` labels. 
 
 Thank you

**Comment by skmirajulislam** [comment]
@iamsaura8h resolved this issue!
