### ISSUE TITLE
Adding Hovering effect on cards.

### ISSUE THREAD

**Issue by Son7c** [Vin205/Enyanjyoti#148]
In this section there is no hovering effect.
Assign this to me i would like to contribute in this.

Before
https://github.com/user-attachments/assets/cedc6633-9375-426a-b785-c0e77b4d2aa8

After
https://github.com/user-attachments/assets/4d4972f2-daf1-4df7-9e09-e69004f5eb4e

**Comment by skmirajulislam** [comment]
@Son7c  check it currently, in this version website already having this features !
