### ISSUE TITLE
ADD HOVER EFFECT TO THE IMAGES 

### ISSUE THREAD

**Issue by sahhoArjun097** [Vin205/Enyanjyoti#15]
I CAN ADD HOVER ANIMATION EFFECT TO THE IMAGES TO MAKE IT ATTRACTIVE.

![image](https://github.com/user-attachments/assets/a7cc9c32-bbf7-48ba-a68b-5d6d89e3d1ff)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant  and lvl.

**Comment by HarjotSH** [comment]
I would like to handle this issue. Please assign me the project ASAP.

**Comment by sahhoArjun097** [comment]
@Vin205 please assign me this issue

**Comment by skmirajulislam** [comment]
@sahhoArjun097 and @HarjotSH you both are assigned!

**Comment by ritikm31** [comment]
please assign it to me .

**Comment by skmirajulislam** [comment]
@ritikm31 create new issue please already fulfilled by @HarjotSH @sahhoArjun097

**Comment by HarjotSH** [comment]
Yes, I will do this @sahhoArjun097

**Comment by skmirajulislam** [comment]
> Yes, I will do this @sahhoArjun097

follow the #37

**Comment by ritikm31** [comment]
ok, I'm gonna create a new one.

**Comment by HarjotSH** [comment]
> > Yes, I will do this @sahhoArjun097
> 
> follow the #37

ok bro

**Comment by sahhoArjun097** [comment]
UI of hero section is already updated
