### ISSUE TITLE
improve routing

### ISSUE THREAD

**Issue by STXRSHIVA** [Vin205/Enyanjyoti#150]
Since our app is made with react our app should be a single page application and i can see that whenever i go to another page the page refreshes

https://github.com/user-attachments/assets/1e8daf6f-8231-4285-800b-57c0529fe0cc

PLease assign me i'll try to fix it

**Comment by skmirajulislam** [comment]
@STXRSHIVA it's because of React router components, furthermore if you able to fix it do it your side and raise your PR.

**Comment by skmirajulislam** [comment]
@STXRSHIVA how its gives any output without any source, run inside frontend folder not inside local repository!

**Comment by STXRSHIVA** [comment]
thanks got it

**Comment by skmirajulislam** [comment]
resolved!
