### ISSUE TITLE
Implement User Login and Signup Routes with JWT Authentication in Backend

### ISSUE THREAD

**Issue by tejasbenibagde** [Vin205/Enyanjyoti#155]
**Objective:**  
We need to set up the backend routes for user login and signup using JSON Web Tokens (JWT) for authentication.

**What We Need to Do:**

1. **User Signup Route:**
   - Create a route that allows users to register.
   - Validate the user input (like checking email format and password strength).
   - Make sure to hash passwords before saving them to the database.
   - Return a JWT when the signup is successful.

2. **User Login Route:**
   - Set up a route for users to log in.
   - Validate the user credentials (like checking the email and password).
   - Upon successful login, return a JWT that users can use for authenticated requests later on.

**A Few Things to Keep in Mind:**
- Handle error responses nicely (for example, if a user already exists or if the credentials are invalid).
- Think about using middleware to verify JWTs on any protected routes.

**Acceptance Criteria:**
- The routes should work correctly and provide appropriate responses.
- The JWT should be generated and verified properly.
- Please include tests to ensure that the login and signup functionality is working as expected.

Please assign me to this task.

**Comment by skmirajulislam** [comment]
@tejasbenibagde assigned!

**Comment by tejasbenibagde** [comment]
Ok Thank you but before starting into this can you tell me how should a user schema look like? like what fields I should add to the user model ?

**Comment by skmirajulislam** [comment]
const UserSchema = new mongoose.Schema({
  userName: {
    type: String,
    required: true,
    unique: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
  role: {
    type: String,
    default: "user",
  },
});

**Comment by tejasbenibagde** [comment]
Ok
