### ISSUE TITLE
DOC: Add Code of Conduct for Enyanjyoti Website

### ISSUE THREAD

**Issue by HarshadaGirase** [Vin205/Enyanjyoti#16]
Description:
A Code of Conduct document needs to be added to the Enyanjyoti website's repository to outline the expected behavior and guidelines for contributors. This document will help ensure a positive, inclusive, and respectful environment for all community members.

Expected Outcome:
The CODE_OF_CONDUCT.md file should be available in the repository, and contributors should be informed about the standards and practices for contributing to the project.

Purpose:
To ensure a safe, welcoming, and professional environment for all contributors and users of  Enyanjyoti

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by skmirajulislam** [comment]
@HarshadaGirase I'm assigning this task to you. Please follow GSSOC guidelines while drafting the **CODE_OF_CONDUCT.md**. This document will help maintain a positive and respectful environment. Once ready, submit it via a pull request. Let me know if you need any assistance!

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!

**Comment by skmirajulislam** [comment]
@HarshadaGirase changes is merged to main!

**Comment by skmirajulislam** [comment]
@prisha-sh yes in what type of contribution you're interested, please make an issue on it hopefully if its unique well assign you for contribution.
