### ISSUE TITLE
Improve the UI of the 404 page

### ISSUE THREAD

**Issue by amitroy-thedev** [Vin205/Enyanjyoti#160]
![image](https://github.com/user-attachments/assets/f9de8716-a191-4409-b743-a9da913ffb96)

Currently the 404 page is not as it should be, i want to make the improve the ui

**Comment by skmirajulislam** [comment]
@amitroy-thedev assigned!

**Comment by amitroy-thedev** [comment]
![image](https://github.com/user-attachments/assets/68cf7833-6cab-486f-a102-88ffe072df6d)
is it looks good or should i also add logo?

**Comment by skmirajulislam** [comment]
@amitroy-thedev okey
