### ISSUE TITLE
make UI responsive and solve logo issue ⭐

### ISSUE THREAD

**Issue by skmirajulislam** [Vin205/Enyanjyoti#163]
![Screenshot 2024-10-09 182749](https://github.com/user-attachments/assets/920dd819-448f-4e14-a6a1-e79df71616b6)
![Screenshot 2024-10-09 182902](https://github.com/user-attachments/assets/42735274-1797-41b6-a439-3f45939d34b7)
![Screenshot 2024-10-09 182935](https://github.com/user-attachments/assets/594f3ba9-9deb-4c50-8361-03948f6569da)
![Screenshot 2024-10-09 183150](https://github.com/user-attachments/assets/d78a41b1-1321-48a8-8c8f-0f6b26c08b5f)

fix it make it phone responsive! and when user clicks on the logo it appears why fix it too !

**Comment by shivam-thedev** [comment]
please assign to me ,will solve this

**Comment by skmirajulislam** [comment]
@shivam-thedev assigned!

**Comment by skmirajulislam** [comment]
@shivam-thedev resolved!
