### ISSUE TITLE
want to change logo and nav bar

### ISSUE THREAD

**Issue by devki412** [Vin205/Enyanjyoti#175]
Hey @Vin205 ,

I want  to  redesign navbar  and logo it not suits the website landing page. 
<img width="924" alt="image" src="https://github.com/user-attachments/assets/ef9d52f9-0807-4e87-9d39-27d9d7fcd7c2">

Can you please assign me this issue.

**Comment by skmirajulislam** [comment]
@devki412 provide some example of your proposal!
