### ISSUE TITLE
Strong password

### ISSUE THREAD

**Issue by Ashishkr8802** [Vin205/Enyanjyoti#182]
In the sign up page when we enter the password it should be strong , currently it's taking even single letter password but it should be employ a mix of uppercase and lowercase letters, numbers, and symbols.

I can fix this issue please assign me this issue
![Screenshot 2024-10-10 203705](https://github.com/user-attachments/assets/6e2164c1-cc2e-48c2-8abb-ad3d7b006f2b)

**Comment by skmirajulislam** [comment]
@Ashishkr8802 assigned!

**Comment by skmirajulislam** [comment]
resolved!
