### ISSUE TITLE
Improvement in the Navbar

### ISSUE THREAD

**Issue by shanvid19** [Vin205/Enyanjyoti#184]
hey @Vin205 !

I would like to work on the navbar of the website. 

- I'll make it more appealing by changing it's colour to black and by adding more elements to it, namely sign in and login buttons.

![Screenshot 2024-10-10 205251](https://github.com/user-attachments/assets/aa544319-249d-44d7-af2b-dd58f4f98906)

- Not only this, but I'll also work on the navbar which appears on the mobile version of the website, and add a little more margin to the elements of navbar to make it more attractive.

![Screenshot 2024-10-10 205759](https://github.com/user-attachments/assets/2b9ac7d8-c7c2-42d0-a332-3013d6398dfe)

Please assign me this issue under the labels 'gssoc-ext' and 'hacktoberfest-accepted'.
Thanks!

**Comment by skmirajulislam** [comment]
@shanvid19 assigned!

**Comment by skmirajulislam** [comment]
@shanvid19 resolved!
