### ISSUE TITLE
Issue in the Footer in Mobile Version

### ISSUE THREAD

**Issue by shanvid19** [Vin205/Enyanjyoti#185]
Hey @Vin205 !

I would like to work on the footer which appears in the mobile version of the website.

![Screenshot 2024-10-10 210039](https://github.com/user-attachments/assets/98f760c4-7308-4981-bb48-7662a14d9cfd)

Currently, these buttons in the footer are not working as well as they are not even properly visible. Additionally, I'll also work on the colour of footer as it can be improved.

Please assign me this task under 'gssoc-ext' and 'hacktoberfest-accepted'
Thanks!

**Comment by skmirajulislam** [comment]
@shanvid19 sorry to say you this issue is resolved in new version of website, kindly check it !
