### ISSUE TITLE
Issue in the responsiveness of the website

### ISSUE THREAD

**Issue by shanvid19** [Vin205/Enyanjyoti#186]
Hi @Vin205 !

I would like to work on responsiveness of the about us and contact us pages.

![Screenshot 2024-10-10 210700](https://github.com/user-attachments/assets/07055f4d-ee96-4f6c-b943-9b62aee527c6)
![Screenshot 2024-10-10 210713](https://github.com/user-attachments/assets/5acb78c7-0a7a-4a98-aee0-17b1658b289f)

As shown in the above screenshots, currently, the pages are unable to adapt properly to the dimensions when viewed on a mobile. I'll make them properly responsive.

Please assign me this issue under the labels 'gssoc-ext' and 'hacktoberfest-accepted'
Thanks!

**Comment by skmirajulislam** [comment]
@shanvid19 already resolved, kindly check final version of this project!
