### ISSUE TITLE
Logo looks very small in navbar

### ISSUE THREAD

**Issue by keerthana2-005** [Vin205/Enyanjyoti#187]
logo looks very small in navbar it doesnt look nice
![image](https://github.com/user-attachments/assets/e1f0c7eb-4f97-4d2e-a950-b996e3242ac3)

plz add level,hacktoberfest and gssoc 2024 extnd

**Comment by skmirajulislam** [comment]
@keerthana2-005 assigned, before going it to, provide an demonstration!

**Comment by rakhiiprajapati** [comment]
Hello is please assign me this issue
