### ISSUE TITLE
Title: Add Pre-commit Hook to Run Prettier and ESLint

### ISSUE THREAD

**Issue by tejasbenibagde** [Vin205/Enyanjyoti#188]
I’d like to propose adding a pre-commit hook to our backend application. This hook would run both **Prettier** and **ESLint** before any commits are made. Here’s why I think this is a great idea:

- **Consistency**: By automatically formatting code with Prettier and checking for linting issues with ESLint, we can ensure that our code remains consistent across the team.
  
- **Efficiency**: This setup can help catch formatting and linting issues before they make it into the codebase, reducing the time spent during code reviews.

- **Simplicity**: Having these tools run automatically means developers won’t have to remember to run them manually. It streamlines our workflow!

Implementing this change could greatly enhance our development process and maintain code quality.

**Comment by skmirajulislam** [comment]
@tejasbenibagde assigned

**Comment by skmirajulislam** [comment]
@tejasbenibagde resolved!
