### ISSUE TITLE
Design and Implement a Fully Responsive 'About Us' Page

### ISSUE THREAD

**Issue by sahhoArjun097** [Vin205/Enyanjyoti#19]
I would like to contribute by designing and implementing a modern, visually appealing, and fully responsive 'About Us' page for the website. This page will enhance the user experience by providing an elegant layout that showcases the website's mission, vision, and team, while maintaining responsiveness across all devices.![image](https://github.com/user-attachments/assets/f8eb1edb-3842-4982-9006-426fad9539f2)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

**Comment by skmirajulislam** [comment]
@sahhoArjun097  Approved! You have been assigned the task. Feel free to start working on it, and reach out if you have any questions.

**Comment by sahhoArjun097** [comment]
hello i need help related to about page

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!

**Comment by sahhoArjun097** [comment]
@skmirajulislam  please reply me soon

**Comment by skmirajulislam** [comment]
@sahhoArjun097 yes how can assist you!

**Comment by skmirajulislam** [comment]
@sahhoArjun097 resolved this issue!

**Comment by sahhoArjun097** [comment]
which issue

**Comment by skmirajulislam** [comment]
#98 PR assigned issue, means this one im talking about GitHub issue number not in code issue😂, dont worry.

**Comment by sahhoArjun097** [comment]
okay
