### ISSUE TITLE
Missing 'Contact Us' Form in Footer Section

### ISSUE THREAD

**Issue by Ayan-Khan79** [Vin205/Enyanjyoti#190]
The website has a dedicated "Contact Us" page, but there's no smaller version of the contact form in the footer section. Adding a simple contact form to the footer would enhance user experience by providing an easy way for visitors to reach out from any page.

![image](https://github.com/user-attachments/assets/66d4d37f-72d3-4293-82b9-f2395634c301)

Suggested Enhancement:
Add a small contact form in the footer with the following fields:

Name (text input)
Email (email input)
Message (textarea)
Submit button

Expected Behavior:
The contact form should allow users to send quick messages from any page without needing to navigate to the full "Contact Us" page.

@Vin205 Can you please assign me this issue under gssoc and hacktoberfest and level label...

**Comment by divyanshivats** [comment]
I woyld like to work on it. Please assisgn it to me
