### ISSUE TITLE
Navigation bar chaning

### ISSUE THREAD

**Issue by rakhiiprajapati** [Vin205/Enyanjyoti#191]
![Screenshot (92)](https://github.com/user-attachments/assets/b4c85812-f053-4d62-a3a1-5b8865c884d5)
Logo are little small and add the search bar

**Comment by skmirajulislam** [comment]
@rakhiiprajapati assigned!

**Comment by rakhiiprajapati** [comment]
Dear sir ,



Hello sir I am changing the game logo
Sir please guide me how to contribute many more

**Comment by skmirajulislam** [comment]
@rakhiiprajapati yes how i can assist you ?

**Comment by rakhiiprajapati** [comment]
Thank you for your response.

**Comment by rakhiiprajapati** [comment]
Awesome, thanks for the update!
