### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [Vin205/Enyanjyoti#193]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@Vin205 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this isssue.

**Comment by skmirajulislam** [comment]
@tarunkumar2005 assigned!

**Comment by tarunkumar2005** [comment]
@harshbhar0629 This is for the contributors page on website not on readme
