### ISSUE TITLE
Optimize footer size and enhance navbar design

### ISSUE THREAD

**Issue by kekubhai** [Vin205/Enyanjyoti#199]
Oversized Footer: The footer section is currently occupying an excessive amount of space on the page. This may be pushing important content further down and affecting the overall user experience. We need to reduce its size to make better use of the available screen real estate.

Plain Navbar Design: The navigation bar appears too simplistic and lacks visual appeal. This could potentially impact user engagement and the overall aesthetic of our application. We should consider enhancing its design to make it more attractive and user-friendly.

Proposed Actions:

Reduce the footer's height and/or width as appropriate
Reorganize footer content to be more compact if necessary
Redesign the navbar with improved styling (e.g., colors, shadows, hover effects)
Consider adding icons or other visual elements to the navbar to make it more engaging
Please provide any additional context or specific design preferences to guide the improvements.

Screenshots of the current footer and navbar would be helpful if available."
![image](https://github.com/user-attachments/assets/fcbb22c4-9e94-48ba-8c61-ee947cfe6b54)
, Please assign me this issue, I would love to work on these

**Comment by skmirajulislam** [comment]
@kekubhai assigned!

**Comment by skmirajulislam** [comment]
@kekubhai resolved!
