### ISSUE TITLE
Lets'Work

### ISSUE THREAD

**Issue by Sameeratweb** [Vin205/Enyanjyoti#2]
![Screenshot 2024-10-02 064109](https://github.com/user-attachments/assets/8220fd1e-3dba-4e26-8047-f751f688328e)
Things Doesnt Look well , there several issues in webpage .Give me chance to work on this project for better responsiveness and UI on frontend part.

i would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

**Comment by skmirajulislam** [comment]
Hi @Sameeratweb , 

What type of contribution are you interested in making for this project? Let me know your ideas or specific areas you’d like to work on!
