### ISSUE TITLE
FAQ transition

### ISSUE THREAD

**Issue by saumyayadav25** [Vin205/Enyanjyoti#200]
While clicking on the question present in FAQ, it opens abruptly, same while closing.

Smooth animation or transition can be applied for better user experience.

Please do let me know if the issue is assigned to me.

**Comment by skmirajulislam** [comment]
@saumyayadav25 Assigned!

**Comment by saumyayadav25** [comment]
after npm run dev, it's showing src/main.jsx does'nt exist
