### ISSUE TITLE
[feat] : Improve login.js features for faster loading times and readability

### ISSUE THREAD

**Issue by Yash-Vashishth** [Vin205/Enyanjyoti#203]
Hi @Vin205 !! I saw your code and all major changes have been taken care of. I just want to suggest some changes in the login.js file to:- 

1. **Separation of Concerns** : The Login.js file is broken down into smaller sub-components (LoginHeader, LoginForm, LoginFooter) for 
    better readability and maintainability.
2. **Consistent Naming Conventions** : Consistent and descriptive naming conventions are used for state variables and functions.
3. **Code Efficiency** : The code is structured in a way that avoids unnecessary re-renders and optimizes state updates.
4. **Error Handling** : Enhanced error handling is included to provide more detailed feedback to users.
5. **User Experience** : The loading state and accessibility are considered to improve the user experience.

This requires many changes but it enhances the overall quality of the code and readability of code.Please assign me this issue.

Thanks,
Yash Vashishth
(Contributor, GSSoC'24(Ext) and Hacktoberfest)

**Comment by Yash-Vashishth** [comment]
P.S. :- PLease add the labels of gssoc-ext, hacktoberfest (not hacktoberfest-accepted) and level 2 tags to this.
Thank you

**Comment by skmirajulislam** [comment]
@Yash-Vashishth assigned!

**Comment by skmirajulislam** [comment]
@Yash-Vashishth resolved!
