### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by rajatsinghal02** [Vin205/Enyanjyoti#21]
I want to update the Readme.md file so that users can easily understand the project.

@Vin205 Please assign this issue to me..

**Comment by skmirajulislam** [comment]
@rajatsinghal02 Sure, I'll assign this issue to her under GSSOC'24 Extended and Hacktoberfest.

**Comment by swatified** [comment]
@skmirajulislam Can you assign me too?

**Comment by skmirajulislam** [comment]
@swatified  Please ensure that someone has already submitted a pull request for this. If there isn't one, it's important to provide better visibility on the existing PR. Otherwise, there won't be any points awarded to either of you. you've assigned

**Comment by skmirajulislam** [comment]
#37

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!
