### ISSUE TITLE
ADD NEW UI TO THE LOGIN PAGE 

### ISSUE THREAD

**Issue by HS202022** [Vin205/Enyanjyoti#214]
![Screenshot 2024-10-12 012046](https://github.com/user-attachments/assets/82a8bdca-a678-4f42-ac9c-d2660580fade)
![Screenshot 2024-10-12 012041](https://github.com/user-attachments/assets/fe6e230e-27db-4bf6-b259-f8448b59e2fa)
SOME SAMPLE WORKS 
https://github.com/user-attachments/assets/fe7253d9-dd21-46e0-a5ad-e1615d78ab48

**Comment by skmirajulislam** [comment]
@HS202022 Assigned!
