### ISSUE TITLE
Contact us backend is not there.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Vin205/Enyanjyoti#215]
So contact us backend is not there. So i can implement the contact us backend such that user can fill the form and the response should go to the project admin mail using nodemailer and backend api.

so assign issue under gssoc and hactoberfest.

**Comment by skmirajulislam** [comment]
@VinayLodhi1712 asssigned!

**Comment by VinayLodhi1712** [comment]
i have work on this or not.
