### ISSUE TITLE
Revamp the Existing Navbar 

### ISSUE THREAD

**Issue by shubhagarwal1** [Vin205/Enyanjyoti#216]
<img width="1416" alt="Screenshot 2024-10-12 at 2 23 53 AM" src="https://github.com/user-attachments/assets/0481b234-f31e-4908-91cf-0c12e54567cd">
As of now it looks if the code is buggy or some how css is not set properly 
hey @Vin205  please assign me this task.

**Comment by skmirajulislam** [comment]
@shubhagarwal1 assigned!
