### ISSUE TITLE
ADD a page for Career

### ISSUE THREAD

**Issue by shubhagarwal1** [Vin205/Enyanjyoti#217]
<img width="465" alt="Screenshot 2024-10-12 at 2 27 03 AM" src="https://github.com/user-attachments/assets/8e17623d-019b-4114-8ed4-786891a5609f">
as clicking on the carrer page takes us to no where so, i porpose to add a new carrer page.
hey @Vin205 please assign me this task

**Comment by skmirajulislam** [comment]
@shubhagarwal1 assigned!
