### ISSUE TITLE
Enhance the look and feel of the footer 

### ISSUE THREAD

**Issue by shubhagarwal1** [Vin205/Enyanjyoti#220]
<img width="1433" alt="Screenshot 2024-10-12 at 2 30 07 AM" src="https://github.com/user-attachments/assets/e5a7805d-1fbe-4fea-be15-72f1a9b96c7c">
as of now the footer is very inconsitent i propose to make it clean and add more things to it such as git repo links social media links which are already presnt and yet to be added 
hey @Vin205 please assign me this tas

**Comment by skmirajulislam** [comment]
@shubhagarwal1 assigned!
