### ISSUE TITLE
Revamp Loan and Grant page 

### ISSUE THREAD

**Issue by shubhagarwal1** [Vin205/Enyanjyoti#221]
<img width="398" alt="Screenshot 2024-10-12 at 2 31 39 AM" src="https://github.com/user-attachments/assets/fe5e155e-ecbd-4495-8563-42a27b5d9694">
as of now clicking on the button takes us no where i propoise to add a page dedicated o loans and grants
hey @Vin205 please assign me this task

**Comment by skmirajulislam** [comment]
@shubhagarwal1 ASSIGNED! LONE PAGE ALREADY EXIST PLEASE LINK IT UPDATE IT IF YOU WANT!
