### ISSUE TITLE
feature: signin with google option(frontend)

### ISSUE THREAD

**Issue by Palmistry2310** [Vin205/Enyanjyoti#231]
rightnow there is no sign up/login with google option available on both pages.

adding sign up with google(frontend) option-btn and login with google(frontend) option-btn on both the login and sign up page.

![Screenshot 2024-10-12 211329](https://github.com/user-attachments/assets/7b186bd4-dc33-4631-9240-cb24123cfdb5)
![Screenshot 2024-10-12 211349](https://github.com/user-attachments/assets/2eee89e5-8e7c-4dab-991a-2f7bd2c2b7a4)

@Vin205 can you please assign this issue to me under the gssoc-ext, hacktoberfest-accepted and level labels?

**Comment by skmirajulislam** [comment]
@Palmistry2310 ASSIGNED!
