### ISSUE TITLE
Scroll bar is default which is not suited on your website

### ISSUE THREAD

**Issue by VinayLodhi1712** [Vin205/Enyanjyoti#232]
I will create a dynamic well suited scroll bar for your website.

![againscrollbar](https://github.com/user-attachments/assets/dd8a602f-143b-409c-8c0c-3fa737cfca71)

https://github.com/user-attachments/assets/97305f7c-0772-44de-80f7-2e62cfee299b

**Comment by skmirajulislam** [comment]
@VinayLodhi1712 ASSIGNED!
