### ISSUE TITLE
feature: Footer for login page and signup page

### ISSUE THREAD

**Issue by Palmistry2310** [Vin205/Enyanjyoti#233]
Right now login and sign up page lacks footer which creates inconsistency with the other pages of the website.
I will be creating the footer and adding it to both the pages , so that uniformity across all the pages remains intact.
@Vin205 can you please assign this issue to me under gssoc-ext, hactoberfest-accepted, and level label?

**Comment by skmirajulislam** [comment]
@Palmistry2310 assigned!

**Comment by skmirajulislam** [comment]
@HarshadaGirase RESOLVED!
