### ISSUE TITLE
Feature: Adding Privacy Policy page to the website

### ISSUE THREAD

**Issue by Palmistry2310** [Vin205/Enyanjyoti#240]
Privacy policy page is an important document for any website and I would like to create one for this website.

**Comment by Palmistry2310** [comment]
@skmirajulislam i will make the page responsive if you consider upgrading the level. Please let me know!

**Comment by TanmayKalra09** [comment]
@Palmistry2310  can I pick up this issue further or are you working on it?
cc: @skmirajulislam
