### ISSUE TITLE
Untidy Nav Bar with no padding

### ISSUE THREAD

**Issue by ParulPrashar** [Vin205/Enyanjyoti#255]
The nav bard does not look good at all due to unwanted elements placed below each link like about etc. moreover there is no padding in nav bar leading to smaller size and height. Below is image attached for reference.

![Screenshot (29)](https://github.com/user-attachments/assets/b5627f26-a213-45c7-b641-611cb94c84d8)

@Vin205  Kindly assign this issue to me under labels gssoc and hacktoberfest.

**Comment by skmirajulislam** [comment]
@ParulPrashar assigned!
