### ISSUE TITLE
[FEAT]: Add Additional Routes to Backend

### ISSUE THREAD

**Issue by tejasbenibagde** [Vin205/Enyanjyoti#256]
Currently, our backend only includes authentication routes. To expand functionality and align with the project's objectives, I plan to add the following routes:
1. Routes for creating and removing courses.
2. Routes for managing notifications.
3. Routes for handling bookmarks.

These additional routes will provide the necessary endpoints to support key features and improve the overall functionality of the application.

**Comment by hkpatel321** [comment]
I would like to help for  adding the functionality of routes

**Comment by skmirajulislam** [comment]
both awarded if you able to resolve it!
