### ISSUE TITLE
Fixing alignment in the contact us page along with navbar

### ISSUE THREAD

**Issue by ayushijainn111** [Vin205/Enyanjyoti#259]
<img width="852" alt="Screenshot 2024-10-13 133408" src="https://github.com/user-attachments/assets/992a65a1-5f3d-4542-9f78-73fdc2d29c95">
i would like to fix the spacing and the alignment 
Assign me this @ArchanRD

**Comment by ArchanRD** [comment]
Hey @ayushijainn111 I am a also a contributor like you. I am not the project admin and so I cannot assign this task to you.

**Comment by skmirajulislam** [comment]
@ArchanRD assigned!
