### ISSUE TITLE
Feature Request: Create a User Profile Card Component for the Dashboard

### ISSUE THREAD

**Issue by priyanshi-codes** [Vin205/Enyanjyoti#26]
### I would like to implement a ProfileCard component that displays user details such as name, role, and provides an option to edit profile information. This component will be used across the student, educator, and admin dashboards.

**Comment by skmirajulislam** [comment]
@priyanshi-codes assigned for this issue!

**Comment by skmirajulislam** [comment]
#37

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!

**Comment by priyanshi-codes** [comment]
Hi, @prisha-sh I have already started working on it...

**Comment by skmirajulislam** [comment]
@prisha-sh please create an issue by yourself, this issue is already fulfilled by  @priyanshi-codes

**Comment by skmirajulislam** [comment]
@priyanshi-codes resolved this issue!
