### ISSUE TITLE
To fix navbar options 

### ISSUE THREAD

**Issue by pallaviii21** [Vin205/Enyanjyoti#261]
![Screenshot 2024-10-13 160245](https://github.com/user-attachments/assets/a83f1ac3-2559-40d5-9cac-aacbc66998ee)
To fix navbar options 

Assign this issue @Vin205

**Comment by harshita-2003** [comment]
pleas assign this issue to me

**Comment by skmirajulislam** [comment]
@harshita-2003 sorry someone already done this !
