### ISSUE TITLE
Typing Mistake: Rename of Nabar.js to Navbar.js and change of title from react app to e-nyanjyoti

### ISSUE THREAD

**Issue by anurags10** [Vin205/Enyanjyoti#27]
@skmirajulislam can you please assign this to me. This file is for the navbar to help users understand its purpose.
Will change it's corresponding CSS file name.

**Comment by skmirajulislam** [comment]
@anurags10 there is no point will be awarded for this!, its very negligible

**Comment by anurags10** [comment]
@skmirajulislam i will change title from react app to e-nyanjyoti in this issue.
will it be fine?

**Comment by skmirajulislam** [comment]
@anurags10 assigned !

**Comment by anurags10** [comment]
@skmirajulislam I have also replaced react favicon and added a new favicon below 
<img width="193" alt="Screenshot 2024-10-04 at 8 45 14 PM" src="https://github.com/user-attachments/assets/9885c231-f07a-4cc8-935f-27382b27a510">
will it be fine?

**Comment by skmirajulislam** [comment]
@anurags10 good job , can you please make that favicon round shape

**Comment by anurags10** [comment]
@skmirajulislam  PR raised.

**Comment by skmirajulislam** [comment]
Ok wait
