### ISSUE TITLE
BUG: ContactUs Section hide

### ISSUE THREAD

**Issue by harshbhar0629** [Vin205/Enyanjyoti#276]
Contact us section hide by navbar of the website it don't show the whole page of contactUs.

UI of ContactUs Page:

https://github.com/user-attachments/assets/8c3cd17c-cbb8-474a-97e1-f00ed62e55ce

@skmirajulislam Please assign this issue to under gssoc-ext, hacktoberfest-accepted with level-2.

**Comment by harshbhar0629** [comment]
@skmirajulislam ??

**Comment by skmirajulislam** [comment]
@harshbhar0629 assigned!

**Comment by harshbhar0629** [comment]
??
