### ISSUE TITLE
 Improve Message Display and Validate Character Length on "Contact Us" Page

### ISSUE THREAD

**Issue by ananyag309** [Vin205/Enyanjyoti#280]
Display Message After Submission:
Currently, there is no clear indication of a successful submission. We should display a confirmation message after the user submits their inquiry.

Character Length Validation:
Implement character length validation on the message field to ensure that users cannot submit messages that are too short (e.g., 1 character). A minimum character limit should be set (e.g., 10 characters) to encourage users to provide more meaningful feedback.

**Comment by Satishmirjan** [comment]
Hi, could you please assign this issue to me? I'd love to contribute as part of Hacktoberfest.

**Comment by skmirajulislam** [comment]
@ananyag309 assigned!
