### ISSUE TITLE
enhance the ui of signup portal

### ISSUE THREAD

**Issue by ananyag309** [Vin205/Enyanjyoti#281]
enhance the ui of currently existing signup portal

![image](https://github.com/user-attachments/assets/4df1f413-0c0f-4a86-b7c3-e53163a9a10f)

**Comment by Satishmirjan** [comment]
I will do  it. please assign me this.

**Comment by skmirajulislam** [comment]
@ananyag309 assigned!

**Comment by RohithNair27** [comment]
Hi @Satishmirjan,
Are you still working on this? If not let me know 

Thanks ; )

**Comment by Khushi-rana310** [comment]
hi, I want to work on this project please assign me this.
