### ISSUE TITLE
Fixing navbar on login/signup page

### ISSUE THREAD

**Issue by Devanshu1603** [Vin205/Enyanjyoti#286]
Navbar is overriding login/signup page content .
![Screenshot 2024-10-14 021849](https://github.com/user-attachments/assets/567bc638-733a-418c-80f4-ee74a654c3a8)
![Screenshot 2024-10-14 022011](https://github.com/user-attachments/assets/5e1e8184-26c4-4cdc-954f-ba64bc9fa2df)
@skmirajulislam  please assign it to me under gssoc-extended , hacktober fest accepted and with appropriate levels.

**Comment by skmirajulislam** [comment]
@Devanshu1603 assigned!
