### ISSUE TITLE
Fix: Home Page Section Repeats Twice on Website

### ISSUE THREAD

**Issue by Agnish1611** [Vin205/Enyanjyoti#29]
**Issue Description:**
The home page of the website is displaying a specific section twice, leading to unnecessary repetition of content. This issue needs to be addressed to ensure the website provides a cleaner user experience. The task involves identifying the root cause (potentially duplicate HTML elements or incorrect rendering logic in the code) and resolving it by either removing the duplicated section or correcting the rendering process.

**Steps to reproduce:**
- Navigate to the home page of the website.
- Scroll through the content to observe the repetition.

**Expected Outcome:**
The home page section should appear only once to maintain a proper layout.

**Actual Outcome:**
The home page section is repeating twice, affecting the flow of the page.

**Environment:**
- Browser: Chrome
- Device: Desktop
- Operating System: Windows

**Screenshots:**

![Screenshot 2024-10-04 212514](https://github.com/user-attachments/assets/bf3b0923-d733-44a0-b793-fac2e9b93f3f)

Please assign this to me and add the necessary tags. I would like to solve this issue for GSSoC Extd. and Hacktoberfest

**Comment by skmirajulislam** [comment]
@Agnish1611 Assigned

**Comment by skmirajulislam** [comment]
Resolved and merged #29
