### ISSUE TITLE
[FEATURE] Add Translation Tool

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Vin205/Enyanjyoti#296]
I want to add a Translation Tool(all language) properly.

@Vin205 PA please assign me this task.

![Screenshot 2024-10-14 152131](https://github.com/user-attachments/assets/6f61ea24-a15e-4c95-b6e2-6ac807130885)

**Comment by Subhajit-2023-44** [comment]
@skmirajulislam ??

**Comment by skmirajulislam** [comment]
sorry someone already working on it

**Comment by Subhajit-2023-44** [comment]
> sorry someone already working on it

Ok
