### ISSUE TITLE
Login / signup section is missing 

### ISSUE THREAD

**Issue by adityalaxkar123** [Vin205/Enyanjyoti#3]

**Comment by adityalaxkar123** [comment]
Me a GSSOC'24 extended member can you assign it to me

**Comment by Ashmita-15** [comment]
can you assign this to me please

**Comment by yogendrakag** [comment]
I see that the login/signup section is missing. As a GSSoC '24 extended member, I would like to work on fixing this issue. Please assign it to me. Thank you!

**Comment by skmirajulislam** [comment]
Hi @Ashmita-15  and @adityalaxkar123 ,

You are both assigned to this issue! Once you've implemented your solutions, I will review the changes and merge the one that is cleaner and more effective. Good luck!

**Comment by skmirajulislam** [comment]
point will be awarded to @adityalaxkar123, congrats for contribution!
