### ISSUE TITLE
Fixing homepage ui

### ISSUE THREAD

**Issue by swatified** [Vin205/Enyanjyoti#31]
I want to improve the ui of homepage:

**CURRENT VERSION**
![Screenshot 2024-10-04 205658](https://github.com/user-attachments/assets/3a925d35-5d93-4225-960e-aeb10a3c8367)
![Screenshot 2024-10-04 205713](https://github.com/user-attachments/assets/9cbe83cb-4204-4d93-8686-08c9a901539c)
![Screenshot 2024-10-04 205727](https://github.com/user-attachments/assets/7cef0da2-c0a6-4bb3-bd89-3d7a0aebb179)

**PROPOSED SOLUTION GLIMPSE**
![Frame 2](https://github.com/user-attachments/assets/33892c5b-cf1d-4f22-8840-2418a76565c1)
![Frame 3](https://github.com/user-attachments/assets/1d171488-7526-4cf3-ac6d-8202458e7111)

**Comment by swatified** [comment]
@skmirajulislam kindly go through the proposed solution and add gssoc-ext, hacktoberfest and level 2 or 3 tag as you wish. So that I can start working on it asap

**Comment by skmirajulislam** [comment]
@swatified assigned!

**Comment by swatified** [comment]
thank you for being active! Will raise a pr soon.

**Comment by swatified** [comment]
I hope you can give level based on the quality of pr. Thank you. See you there

**Comment by skmirajulislam** [comment]
@swatified don't worry after reviewing your contribution, well increase level based on your hardwork, feel free to work , during pull requests make sure to tag me once by explaining contribution 👍🏻. I'll definitely increase your label.

**Comment by skmirajulislam** [comment]
@swatified changes accepted
