### ISSUE TITLE
[Security] Using only reputed mail services for signup's.

### ISSUE THREAD

**Issue by smog-root** [Vin205/Enyanjyoti#312]
Update the existing signup flow to validate email domains. Restrict signups to users with email addresses from trusted providers (e.g., Gmail, Outlook). etc.

Extract the domain from the user's email during signup. Compare it against a predefined list of trusted providers. If the domain matches, proceed with the signup; otherwise, return an error.

**_i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!_**

**Comment by smog-root** [comment]
dude! where is the signup.html and other files of it! in your project??

**Comment by smog-root** [comment]
exactly where?

**Comment by skmirajulislam** [comment]
There is no `signup.html` file; it's built with React, so you'll find the corresponding `.jsx` file instead.

**Comment by skmirajulislam** [comment]
please check our tech stack and frontend folder

**Comment by smog-root** [comment]
i got it! 👍
