### ISSUE TITLE
[Feat] Add a Gallery Slider in About Us or Home Page

### ISSUE THREAD

**Issue by infernodragon456** [Vin205/Enyanjyoti#33]
Hello! I would like to add a Gallery slider to the website, most probably in the About Us/ Home Page which features photos of any thing that the team would like to share. I plan to use an infinite scroll based image slider, and each item would be clickable and would redirect to a blog/ external link.

This would make the site look better and also impress end users!

Please assign me to work on this @skmirajulislam , and add gssoc-ext, hacktoberfest and level 2 or 3 tag as you wish.

**Comment by skmirajulislam** [comment]
@infernodragon456 assigned for this particular issue, based on your pr review we'll increase the point, feel free to work, don't hesitate to ask if anything else

**Comment by skmirajulislam** [comment]
#37

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!

**Comment by skmirajulislam** [comment]
Issue resolved!
