### ISSUE TITLE
Enhance_Real_Time_Password_Validation_in_Signup_Form!

### ISSUE THREAD

**Issue by smog-root** [Vin205/Enyanjyoti#334]
**Criteria**:

- At least 8 characters long
- At least 1 uppercase letter (A-Z)
- At least 1 lowercase letter (a-z)
- At least 1 number (0-9)
- At least 1 special character (e.g., !@#$%^&*())

**Real-Time Validation:**
The validation checks are performed on input to provide immediate feedback on password strength.
Each criterion is validated and indicated individually, allowing users to see which requirements are still unmet.

**_Note_**: i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

**Comment by smog-root** [comment]
Why you added two times gssoc-ext!!

Add level3!

**Comment by saimohan11** [comment]
assign me this task

**Comment by smog-root** [comment]
@saimohan11. i have already asked!! and i don't need any assistance!
