### ISSUE TITLE
[Custom]: Updation Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Vin205/Enyanjyoti#359]
# 💡 Custom Issue

### 📝 Description
The contributing.md looks empty and not in a structured manner. Also some sections are missing.

### 🎯 Expected Outcome
I can update it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

**Comment by shauryaq05** [comment]
Please assign this task to me.
