### ISSUE TITLE
[Feature]: Enhance Contact Us Page

### ISSUE THREAD

**Issue by neeru24** [Vin205/Enyanjyoti#362]
The "Contact Us" form currently lacks hover effects, making it feel static. Adding hover effects to buttons and input fields will enhance the form's interactivity and user experience.

**Expected Behavior:**

- Apply hover effects to the submit button and input fields to make the form more engaging.
- Hover effects could include color changes or subtle shadow effects for visual feedback.

![image](https://github.com/user-attachments/assets/f8e3e520-f504-4fc6-a856-57b89fc23844)

**Comment by shauryaq05** [comment]
Mam, please assign this task to me. I would be very grateful.
