### ISSUE TITLE
[Bug]: Incorrect Redirection on clicking Get Started Button

### ISSUE THREAD

**Issue by Dyfintie** [Vin205/Enyanjyoti#366]
# 🐞 Bug Report

### 📋 Description

Get Started button is not working instead of redirecting the user to the sign up page it redirects the user to 404 pagenotfound.
### ⚙️ Steps to Reproduce
1. when user clicks the get started button they are redirected to sign-up page.

### ✔️ Expected Behavior

User is redirected to Sign-Up page when Get Started button is clicked.
### ❌ Actual Behavior

User is redirected to 404 page not found when Get Started button is clicked.
### 📷 Screenshots

![Screen Recording 2024-10-17 190509](https://github.com/user-attachments/assets/620a1da8-127e-4eaf-b449-fe5b3c190e23)

Position : CONTRIBUTOR

**Comment by muskiagrwal** [comment]
i want to work on this issue .assign me this project
