### ISSUE TITLE
[Feature]: Creation Of Donation Page

### ISSUE THREAD

**Issue by Mandy1200** [Vin205/Enyanjyoti#374]
# 🚀 Feature Request

### 📝 Feature Description

Adding a donation page , to enhance the user experience

### 🔧 How Will This Enhance the App?

As this web is completely based  on education , career , grants and loans . As we their is a larger number of population who were below poverty line so not many of them accessible to the capital/funds , so to help them we should create a donation page for them to declare a charity for them 

### 📦 Suggested Implementation

I will use HTML , CSS and JS for implementation
i would definately recommend to add this another page , and create a link to the main page

### 📸 Additional Context

sample
![Screenshot (62)](https://github.com/user-attachments/assets/18f14869-7dd1-4881-a430-5137b3d5b410)

**Comment by skmirajulislam** [comment]
good I'm impressed !
