### ISSUE TITLE
Issue Title: Add FAQ (Frequently Asked Questions) Page to the Website

### ISSUE THREAD

**Issue by sahhoArjun097** [Vin205/Enyanjyoti#38]
We need to implement a dedicated FAQ (Frequently Asked Questions) page for the website to enhance user experience and provide quick answers to common queries.
Ensure the page is fully responsive and functions well on mobile, tablet, and desktop devices.

![image](https://github.com/user-attachments/assets/535e14a9-def2-4308-922c-c538f0789304)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant  and lvl.

**Comment by skmirajulislam** [comment]
@sahhoArjun097 is assigned for this issue!

**Comment by sahhoArjun097** [comment]
thankyou

**Comment by sahhoArjun097** [comment]
why are not replying me i have a n issue related to about us page

**Comment by skmirajulislam** [comment]
Issue resolved!
