### ISSUE TITLE
Contact Us is missing

### ISSUE THREAD

**Issue by Mayursoni1518** [Vin205/Enyanjyoti#4]
It is crucial to add a Contact Us page to the website, as it fosters user trust, allows for direct communication, and enhances overall engagement. I want you to assign this issue to me under Gssoc Extd '24

**Comment by skmirajulislam** [comment]
@Mayursoni1518 I've assigned the issue for the **Contact Us** page to you under GSSOC Extd '24. This addition will boost user engagement and trust. Points will be awarded upon review.

**Comment by ChauhanAyush04** [comment]
@Vin205 assign me, i will solve it

**Comment by skmirajulislam** [comment]
@ChauhanAyush04 is also assigned!

**Comment by skmirajulislam** [comment]
issue is already resolved by someone!
