### ISSUE TITLE
Bad Responsiveness

### ISSUE THREAD

**Issue by SatyaJaiss** [Vin205/Enyanjyoti#41]
The website is having bad responsive to smaller screen devices, and needs improvement.

![Screenshot 2024-10-05 113145](https://github.com/user-attachments/assets/91f95117-1ec1-424f-9802-fd910239368a)
![Screenshot 2024-10-05 114918](https://github.com/user-attachments/assets/d42fa986-74c2-4e2a-a1eb-d8ed9b5289b4)

@Vin205 Kindly assign it to me. I'll make it responsive.

**Comment by skmirajulislam** [comment]
@SatyaJaiss assigned!

**Comment by skmirajulislam** [comment]
@SatyaJaiss your changes are accepted!
