### ISSUE TITLE
Logo Re-design 

### ISSUE THREAD

**Issue by adityakr0660** [Vin205/Enyanjyoti#42]
The logo doesn't look appealing, so I need to redesign it with a more modern and attractive look. 

![photo_2024-10-05_11-39-56](https://github.com/user-attachments/assets/4bbc7ce3-f55a-4e64-bc91-13f9f34b54b5)

Plz assign to me i can make it look much better

**Comment by skmirajulislam** [comment]
@adityakr0660 is assigned for this issue!

**Comment by ChauhanAyush04** [comment]
@adityakr0660  assign me i will change logo

**Comment by skmirajulislam** [comment]
@adityakr0660 is also assigned whoever give solution earlier they will awarded with point!

**Comment by skmirajulislam** [comment]
@adityakr0660 RESOLVED ISSUE!
