### ISSUE TITLE
Footer UI Update

### ISSUE THREAD

**Issue by SatyaJaiss** [Vin205/Enyanjyoti#43]
the footer of this site need improvement. Using icons of socials instead of Names will make it look attractive. Also, the contents of the footer look skewed. The contents of the footer section should be distributed.

@Vin205 Kindly assign it me, I'll make the valuable changes.
![Screenshot 2024-10-05 113740](https://github.com/user-attachments/assets/52a0a51c-708b-41a0-a14e-04d96e473e22)

**Comment by skmirajulislam** [comment]
@SatyaJaiss is assigned for this issue!

**Comment by skmirajulislam** [comment]
Approved!
