### ISSUE TITLE
[Feature]:  Dark mode is not enable after clicking on toggle button.

### ISSUE THREAD

**Issue by aashutosh585** [Vin205/Enyanjyoti#438]
Hey @skmirajulislam  I want to fix the issue of toggle button and also make some changes in navigation bar.
Navigation icons are not properly visible.

![Screenshot 2024-10-20 165101](https://github.com/user-attachments/assets/d5d166d3-050b-4f81-a975-85cccd9c04ad)

Could you assign me this task, so that I can start working on it.
Please make sure to add labels gssoc-ext, hactoberfest, level1, level2, level3.

**Comment by Raj91027** [comment]
I have fixed this issue and now you can use this toggle button. I have requested to apply changes what i have done through pull request.
