### ISSUE TITLE
[Bug]: Contributors Page Not Loading

### ISSUE THREAD

**Issue by NK-Works** [Vin205/Enyanjyoti#486]
# 🐞 Bug Report

### 📋 Description
The contributors page is not even loading

### ⚙️ Steps to Reproduce
1. Go to main
2. Click contributors
3. See

### ✔️ Expected Behavior
A contributors page where the available contributors should be shown and a link to github is also shown.

### ❌ Actual Behavior
No contributors page

### 📷 Screenshots
![image](https://github.com/user-attachments/assets/7737d9d6-af65-4f88-aeab-2de515c68947)

**Comment by muskiagrwal** [comment]
please assign me this project.i want to work on this project
