### ISSUE TITLE
[Feature]: REDESIGN TEH LOGO 

### ISSUE THREAD

**Issue by dhruthigrao** [Vin205/Enyanjyoti#488]
The current logo for Enyanjyoti lacks the innovative and fresh appeal that reflects our mission. It does not adequately represent our brand identity, which focuses on providing unique solutions and fostering creativity. A redesign is essential to align our visual identity with our core values, enhance brand recognition, and attract our target audience more effectively.

By addressing these points in your discussion or proposal, you can effectively convey the need for a logo redesign that captures the spirit of Enyanjyoti.

![Screenshot 2024-10-22 202159](https://github.com/user-attachments/assets/adfaabcd-ba84-46b7-b8fb-010be43e06a4)

whit this :
![image](https://github.com/user-attachments/assets/03755376-d972-41b3-ab0d-a3f14c97eeb7)

I am  a GSSOC-Ext and Hacktober Fest Contributor.

**Comment by verma2402** [comment]
Assign this to me> I would like to work on this
