### ISSUE TITLE
Designing login / signup page 

### ISSUE THREAD

**Issue by Devanshu1603** [Vin205/Enyanjyoti#49]
There must be a login/signup page please assign me this task under gssoc-extended , hacktober fest and with appropriate level. will be happy to contribute

**Comment by skmirajulislam** [comment]
@Devanshu1603 assigned!, label will be awarded after the review of PR

**Comment by skmirajulislam** [comment]
issue resolved!

**Comment by Devanshu1603** [comment]
@skmirajulislam  but this issue was assign to me and i was working on it

**Comment by skmirajulislam** [comment]
@Devanshu1603 sorry for my bad there are lots of candidates, so please try to fix earlier and raise your updated PR.

**Comment by skmirajulislam** [comment]
@Devanshu1603 resolved this issue!
