### ISSUE TITLE
Improve the Navbar section

### ISSUE THREAD

**Issue by Mayursoni1518** [Vin205/Enyanjyoti#5]
I have noticed that the current Navbar section is quite basic. I would like to raise an issue for this and request it to be assigned to me. Enhancing the Navbar is crucial, as it will significantly improve the overall user experience and navigation on the website.

**Comment by dushyantkanav** [comment]
i can solve this issue

**Comment by skmirajulislam** [comment]
@Mayursoni1518 @dushyantkanav sorry guys someone already assigned for this fee free to contribute in some another functionality!
