### ISSUE TITLE
Fix UI Responsiveness

### ISSUE THREAD

**Issue by Shriya-sinha** [Vin205/Enyanjyoti#50]
![Screenshot 2024-10-05 174641](https://github.com/user-attachments/assets/1809372b-03cf-4615-96d3-a7fd0bad2f72)

The current website lacks proper responsiveness, leading to a suboptimal user experience on mobile devices and smaller screens. This issue aims to:

- Implement a fluid grid layout.
- Ensure responsive navigation.

Also, to enhance the visual appeal and coherence of the career page, I recommend replacing the current images in the card section with theme-specific illustrations.

@Vin205  Kindly assign it me, I would like to work on these issues

**Comment by skmirajulislam** [comment]
@Shriya-sinha is assigned for this issue!

**Comment by skmirajulislam** [comment]
ull get appropriate label after changes are made.
