### ISSUE TITLE
[Feature]: adding a better logo to the website

### ISSUE THREAD

**Issue by Pragati1466** [Vin205/Enyanjyoti#500]
# 🚀 Feature Request

### 📝 Feature Description
A more modern, visually appealing logo for the website is needed to better reflect E-nyanjyoti's core mission of providing education, career opportunities, and financial support. The current logo doesn't fully communicate these values and needs to be replaced with a design that captures the platform's focus areas.

### 🔧 How Will This Enhance the App?
A better logo will:

Improve the visual branding of the platform.
Create a stronger connection with users by representing the core values (education, career, and financial empowerment).
Give the website a more professional look and attract more users by making the branding clearer and more engaging.

### 🎯 Use Cases
User Engagement: New users visiting the site will immediately understand that E-nyanjyoti is focused on conceptual learning, career growth, and financial aid through a clear visual representation.

### 📦 Suggested Implementation
A new logo should incorporate symbols representing:
Education (e.g., books, graduation caps)
Career (e.g., briefcases)
Financial Support (e.g., currency symbols)
Ensure the logo is responsive and scales well across different devices (desktop, mobile, tablet).

### 📸 Additional Context
![new 1](https://github.com/user-attachments/assets/64b5822f-af22-4796-b826-3dd03c975f85)
![new 2](https://github.com/user-attachments/assets/fa21d3a2-df84-4f80-a8d1-0cdcbdacdf9b)
@skmirajulislam @Vin205

**Comment by pameladeysarkar2003** [comment]
@iamendless10 please assign me with this task i want to contribute to it

**Comment by Pragati1466** [comment]
@iamendless10 but i want to do it as i took this issue
