### ISSUE TITLE
Add moving carousel in the about us' gallery section

### ISSUE THREAD

**Issue by swatified** [Vin205/Enyanjyoti#51]
I want to improve the about us page ui and also add an automatically moving carousel there. You can assign me level later. Just assign the issue now. 

**ISSUES HIGHLIGHTED**
![image](https://github.com/user-attachments/assets/d94aecf8-c0ba-4efb-b4c8-4fb504bd8913)
![image](https://github.com/user-attachments/assets/c082b36e-315f-43b2-b1d1-c5fb8713a88c)

**Comment by skmirajulislam** [comment]
@swatified resolved this issue!
