### ISSUE TITLE
[Feature]: Changing the logo 

### ISSUE THREAD

**Issue by Bhoomysingh10** [Vin205/Enyanjyoti#511]
# 🚀 Feature Request

### 📝 Feature Description
Replace the existing logo with a new design to better align with the brand identity and improve visual appeal.

### 🔧 How Will This Enhance the App?
Build a Stronger Connection: A fresh logo that reflects our brand’s personality can help users feel more connected to the app and what it stands for.
Make It Visually Appealing: A modern design will make the app look more inviting and enjoyable to use, creating a better overall experience.
Create a Consistent Look: A well-thought-out logo will tie together our app’s design, giving it a professional and polished feel that users will appreciate.

### 🎯 Use Cases
First Impressions & Brand Recognition: A modern logo creates a positive experience and strengthens brand recall for easier identification.
Visual Hierarchy & Engagement: An updated logo improves visual hierarchy, guiding user attention and enhancing call-to-action effectiveness.
Responsive Design: A logo optimized for all devices ensures visual consistency and improves user experience.
Brand Messaging Alignment: A logo that reflects updated messaging fosters a cohesive and credible visual identity

### 📦 Suggested Implementation
![image](https://github.com/user-attachments/assets/7642fba6-cb89-4d0f-a476-2ca68896d31d)

**Comment by Vin205** [comment]
Make sure thaat the logo aligns properly in navbar

**Comment by Bhoomysingh10** [comment]
sure sir

**Comment by Bhoomysingh10** [comment]
@Vin205 Kindly check!
