### ISSUE TITLE
[Custom]:  improve nav section

### ISSUE THREAD

**Issue by rajnish032** [Vin205/Enyanjyoti#512]
![Screenshot 2024-10-25 232101](https://github.com/user-attachments/assets/5ac41836-e971-4a95-a7c3-a524df97558b)
# 💡 Custom Issue

### 🔍 Steps to Reproduce (if applicable)
1. 
2. 
3.

**Comment by Vin205** [comment]
please provide more detaols how will you redesign the navbar
