### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [Vin205/Enyanjyoti#53]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by skmirajulislam** [comment]
@Shariq2003 assigned, but make sure ill changes itself after any new contribution made by some one , works dynamically.

**Comment by Shariq2003** [comment]
> @Shariq2003 assigned, but make sure it'll changes itself after any new contribution made by some one , works dynamically.

Yes, I have added the script that fetches dynamically for sure, if it somehow not, then I will fix it. Well it will work

**Comment by skmirajulislam** [comment]
Approved!
