### ISSUE TITLE
[Bug]: I found a bug on the navbar

### ISSUE THREAD

**Issue by Hemraj-7** [Vin205/Enyanjyoti#561]
in the navbar **Home** menu and **Loan** menu both are open home page.
when we click on Home menu and when we clicked on the Loan menu then the both the condition it will open home page.

I want to solve this issue please assign me this issue

![Screenshot 2024-11-04 163702](https://github.com/user-attachments/assets/2d043d80-60d6-4d6b-a0ad-714d915468e6)

**Comment by veepanshu-kasana** [comment]
@skmirajulislam I want to contribute to this project on this particular issue. Please assign it to me!

**Comment by nikhilritgithub** [comment]
i would like to work on this please assign this to me.
