### ISSUE TITLE
Updating the Contributors Profile in README.md section.

### ISSUE THREAD

**Issue by Jazz-45** [Vin205/Enyanjyoti#67]
Some of the Profiles of our contributors is missing . I want to update all of those profiles which are missing.

**Comment by skmirajulislam** [comment]
@Jazz-45 assigned, make sure it will show properly and dynamic in nature !

**Comment by Jazz-45** [comment]
Hello Sir , you link 
https://contrib.rocks/image?repo=Vin205/Enyanjyoti&&max=1000&&cachebust=1

is not recognising the latest 3 contributors . Please have a look at this issue so that I Can add a new link which have all the contributors.

**Comment by skmirajulislam** [comment]
> Hello Sir , you link https://contrib.rocks/image?repo=Vin205/Enyanjyoti&&max=1000&&cachebust=1
> 
> is not recognising the latest 3 contributors . Please have a look at this issue so that I Can add a new link which have all the contributors.

follow this https://allcontributors.org/ for implementing this functionality
