### ISSUE TITLE
[FEATURE ENHANCEMENT] Enhancing header and footer to make it attractive

### ISSUE THREAD

**Issue by iamendless10** [Vin205/Enyanjyoti#68]
@Vin205 assign me this work under gssoc-ext and hacktoberfest so i can start working

**Comment by skmirajulislam** [comment]
@iamendless10 assigned under GSSoC & hacktoberfest contribution.

**Comment by iamendless10** [comment]
Okay thanks i can start working now

**Comment by skmirajulislam** [comment]
@iamendless10 resolved this issue!
