### ISSUE TITLE
 improving the README file

### ISSUE THREAD

**Issue by adityakalburgi** [Vin205/Enyanjyoti#7]
Hi!
I'd like to contribute by improving the README file. Could you please assign this issue to me? also add labels of gssoc-ext and hacktoberfest Thanks!

**Comment by skmirajulislam** [comment]
@adityakalburgi great idea! I’ll assign this issue to you

**Comment by skmirajulislam** [comment]
unfortunately im closing this issue because some one already done an PR,m fell free for contributing on some other features!
