### ISSUE TITLE
Dependency Issue: babel-preset-react-app is importing @babel/plugin-proposal-private-property-in-object ⚠️

### ISSUE THREAD

**Issue by skmirajulislam** [Vin205/Enyanjyoti#73]
There appears to be a missing dependency in the babel-preset-react-app package. It is importing the @babel/plugin-proposal-private-property-in-object package without declaring it in its package.json dependencies.

This issue is currently working, possibly due to the way npm/yarn hoists dependencies. However, this behavior could cause issues in certain setups, especially if dependency resolution changes or specific versions are required.

Please ensure that after resolving this issue, the project will continue to work as expected, without any changes to existing functionality.

Under GSSOC EXT & HACTOBERFEST

![Screenshot 2024-10-06 103650](https://github.com/user-attachments/assets/0600fe2b-e5e5-4789-ad03-7645131d9aeb)

**Comment by biswajit-sarkar-007** [comment]
Hi, I'm interested in solving this. Can I be assigned?

**Comment by skmirajulislam** [comment]
@biswajit-sarkar-007 Assigned!

**Comment by skmirajulislam** [comment]
@biswajit-sarkar-007 resolved this issue!
