### ISSUE TITLE
🎉 New Release: Project Structure Updated - Backend Added! 🚀

### ISSUE THREAD

**Issue by skmirajulislam** [Vin205/Enyanjyoti#74]
### 📁 What's New?
We’ve made significant updates to the project structure! A **new backend folder** has been added to the repository to improve scalability and organization. This is a crucial step for the ongoing development of the project.

### 🔧 What You Need to Do:
All contributors, **please make sure to update your local repositories** by running the following command:

```bash
git pull origin main
```

**Important:** If you do not update your local repository, your pull requests **WILL NOT** be accepted. It is essential to keep your version up to date with the new structure.

### 💡 Contribution Guidelines:
1. **Hacktoberfest & GSSoC Participation:** We are open for contributions as part of Hacktoberfest and GSSoC. Please ensure you follow the guidelines for both events while contributing to this repository.
   
2. **Pull Request Requirements:**
   - Ensure your local version is up to date with the latest structure.
   - Follow the **first-come, first-served** principle when claiming issues and submitting pull requests.
   - Make sure your PRs align with the **Hacktoberfest** and **GSSoC** contribution rules for valid submissions.
   
3. **New Features & Bug Fixes:**
   - We’re now accepting contributions for the newly added backend.
   - Check out the [Issues](https://github.com/your-repo/issues) tab for tasks available for contribution.

### ⚠️ Attention:
Any pull requests from outdated repositories will be **rejected**. Please ensure you update your local version before contributing to avoid conflicts and ensure smooth collaboration.

### 🙌 Thank You!
We appreciate your dedication and contributions! Let’s work together to build something amazing and make Hacktoberfest & GSSoC 2024 a huge success!

**Comment by VaibhavKatariya** [comment]
@skmirajulislam @Vin205,

I'm interested in developing the backend, especially since I have hands-on experience with Firebase.

Could you provide a brief overview of what the backend should look like and what technologies we will be using? That would be highly appreciated!

Looking forward to your guidance!

**Comment by skmirajulislam** [comment]
@VaibhavKatariya assigned!
