### ISSUE TITLE
UPDATE alignment of navbar and logo and fix signup and login 

### ISSUE THREAD

**Issue by skmirajulislam** [Vin205/Enyanjyoti#79]
![Screenshot 2024-10-06 141154](https://github.com/user-attachments/assets/27587220-8677-44dc-8efd-e8effeb8eed9)
![Screenshot 2024-10-06 141652](https://github.com/user-attachments/assets/13de2bb1-d04f-4d4b-9300-76f64b73a9c3)
![Screenshot 2024-10-06 141909](https://github.com/user-attachments/assets/ab8f9c85-6d36-455b-9d01-eb7ab5774fe5)

fix it and reduce font size a little. make sure its responsive!

**Comment by ArchanRD** [comment]
@skmirajulislam I have created a [pull request](https://github.com/Vin205/Enyanjyoti/pull/83), pelase have a look at it.

**Comment by skmirajulislam** [comment]
@ArchanRD resolved this issue
