### ISSUE TITLE
Adding more elements to the page

### ISSUE THREAD

**Issue by DuckStruggles** [Vin205/Enyanjyoti#8]
This website is very blank, please assign the task of adding more elements in it to me. Also kindly provide a description of the features/elements you want in the home page.

**Comment by skmirajulislam** [comment]
Hi @DuckStruggles ! 

I’ll assign you the task of adding more elements to the website. For the homepage, please consider including the following features:

1. **Hero Section**: A welcoming banner with a brief description of the platform.
2. **About Us**: A section summarizing the platform's purpose.
3. **Features**: Highlight key features like learning resources, career opportunities, and information on loans and grants.
4. **Testimonials**: User reviews or success stories to build trust.
5. **Call to Action**: Buttons for signing up or exploring features.

Feel free to add any other elements you think would enhance the user experience! Let me know if you have any questions.

**Comment by prisha-sh** [comment]
Hi, I am interested in working on this project, please assign me, and I'll share my solution as soon as you ping me !!

**Comment by skmirajulislam** [comment]
@DuckStruggles sorry to say you that we are closing this issue because of this feature already implemented by someone in recent PR!
