### ISSUE TITLE
Suggestion: Transition to Next.js for Enhanced Performance and Firebase Integration

### ISSUE THREAD

**Issue by VaibhavKatariya** [Vin205/Enyanjyoti#82]
Hi Team,

I noticed the project is currently using separate frontend and backend folders, with React for the frontend. I’d like to suggest switching to **Next.js**, as it allows for building both the frontend and backend in a unified framework. Here's why Next.js could be a better fit:

1. **Fullstack Capabilities**: With Next.js, you can handle both frontend and backend logic, as it includes built-in API routes. This eliminates the need to maintain separate folders for the frontend and backend, streamlining development.

2. **Server-Side Rendering (SSR) & Static Generation**: Next.js supports SSR and static generation out of the box. This can drastically improve performance and SEO, especially beneficial for content-heavy or dynamic pages.

3. **Automatic Code Splitting**: Next.js automatically splits the code, making sure only necessary components are loaded initially, improving page load times.

4. **Improved Developer Experience**: The framework includes features like file-based routing and seamless TypeScript support, making development faster and more efficient.

I also noticed that the Firebase label is added but not yet used. Next.js integrates smoothly with Firebase for features like authentication, database, and hosting, making it easy to manage backend services within the same project.

Let me know your thoughts on this suggestion. I'd be happy to help with the migration if you decide to move forward with Next.js. Additionally, it would be great if you could add labels for **Hacktoberfest** and **GSSoC Level 3** to this issue.

**Comment by skmirajulislam** [comment]
@VaibhavKatariya ,

Thank you for your suggestion! However, this project’s tech stack is based on React.js and is designed to be open for all contributors. Switching to Next.js at this stage could introduce challenges for contributors already familiar with React. also its against rule of hactoborfest and GSSoC

If you're interested in contributing with React, we’d be happy to welcome your involvement! Please feel free to reach out if you have any questions or if you'd like to work on React-based issues.

**Comment by VaibhavKatariya** [comment]
Hi @skmirajulislam ,

Thank you for the clarification! I understand the importance of keeping the project within the planned tech stack and the challenges a migration might introduce, especially considering Hacktoberfest and GSSoC rules.

I’d still love to contribute with React.js and will look for opportunities where I can assist. Please feel free to assign me any React-related tasks or issues that need attention!

Looking forward to keep contributing!

Best regards,  
@VaibhavKatariya

**Comment by skmirajulislam** [comment]
@VaibhavKatariya 

you can implement our backed, till now its empty for this ill give you label 3 under GSSOC & hactoberfest, if you able to implement it without any internal conflict, feel free to ask me!

**Comment by VaibhavKatariya** [comment]
@skmirajulislam,

I'm definitely interested in developing the backend, especially since I have hands-on experience with Firebase.

Could you provide a brief overview of what the backend should look like and what technologies we will be using? That would be highly appreciated!

Looking forward to your guidance!
