### ISSUE TITLE
Nav items are duplicated and re-declaration of import breaking app

### ISSUE THREAD

**Issue by ArchanRD** [Vin205/Enyanjyoti#85]
## Nav items in navbar are duplicated

I can see that contributors might not be working on the latest code on repository, which is causing this issues. 
There are multiple issues which are addressed below.

## Issue No. 1
In a recent pull/merge request #80,the import is re declared causing application to throw an error.
![image](https://github.com/user-attachments/assets/be4e9947-75d7-458f-bfc0-6544fade2666)
![image](https://github.com/user-attachments/assets/059d43c1-95c9-470a-9b5e-6b17a5b9f728)

## Issue No. 2
The nav items are duplicated in navbar
![Screenshot from 2024-10-06 19-16-33](https://github.com/user-attachments/assets/5cc90c09-e160-4e74-895f-684d500d370a)

### Fixes: 
Quick fix can be made, just by removing the duplicates.

## Suggested enhancements
Apart from fixing this issue, I have few enhancements for the web app.

## 1. Strechy cards 
The cards are taking full width evenly. Due to this, the card images are not looking properly.

Issue:
https://github.com/user-attachments/assets/3b4add4f-76d3-43a5-b1e7-c1b2dc938436

Fixes:
This can be fixed by giving a fixed with to cards and changing the `display` to 'flex' instead of grid. 

## 2. Contact page have no form
The contact page doesn't have any form. Without it the page is incomplete.
![image](https://github.com/user-attachments/assets/9edf3087-f8f7-459f-83ac-053e7652f359)

Fixes:
A bootstrap form component can be used which will take care of responsiveness too!

This were few suggestions and fixes from my side. I would definetely like to work on this and infact I have completed few of the above. It would be great if you assign this to me and add labels - gssoc, hacktoberfest.

**Comment by ArchanRD** [comment]
@skmirajulislam This issue contains enhancements as well as broken fixes. Please can you assign it to me?

**Comment by skmirajulislam** [comment]
@ArchanRD make sure two different contributors working on this same issue make sure if you need point make PR earlier. is issue or PR is rejected for others, we are not responsible for this!

**Comment by ArchanRD** [comment]
Yes @skmirajulislam There are issues which looks quite similar but they haven't made any progress. Those issues were opened several hours ago. So I though off to work on that! It will cover all the similar issues at once rather than creating single issue for a bug. Thanks for assigning it to me!

**Comment by skmirajulislam** [comment]
@ArchanRD issue resolved by @Devanshu1603 before you, so that im closing this issue!
