### ISSUE TITLE
Improving Navbar

### ISSUE THREAD

**Issue by Devanshu1603** [Vin205/Enyanjyoti#86]
In navbar options are showing multiple time which harness the UI of website. Will be happy to work on this issue. @skmirajulislam   Please assign me this issue under gssoc-extended , hacktober fest accepted and with appropriate level.
![Screenshot 2024-10-06 193551](https://github.com/user-attachments/assets/d66a8c3e-f7db-471a-8b9d-1f76f43cbead)

**Comment by skmirajulislam** [comment]
@Devanshu1603 resolved this issue!
