### ISSUE TITLE
Toggle change mode button.

### ISSUE THREAD

**Issue by Devanshu1603** [Vin205/Enyanjyoti#87]
There must be a toggle change mode button to change UI of website according to user . @skmirajulislam  Please assign me this under gssoc-extended , hactober fest and with levels, so that a could solve this issue.

**Comment by skmirajulislam** [comment]
@Devanshu1603 ASSIGNED!

**Comment by biswajit-sarkar-007** [comment]
Hi @skmirajulislam ,

Can you please assign this issue to me? I'd like to work on it.

Thanks!

**Comment by skmirajulislam** [comment]
@Devanshu1603 is already assigned!
