### ISSUE TITLE
adding authentication feature

### ISSUE THREAD

**Issue by Sameeratweb** [Vin205/Enyanjyoti#89]
Once the application prompts for login and sign-in, we can work on authentication. Please address this issue with relevant tags under GSSOC and Hacktoberfest.

**Comment by skmirajulislam** [comment]
@Sameeratweb backed ?

**Comment by VaibhavKatariya** [comment]
Hey @Sameeratweb, I am already working on this issue. Thanks for bringing it up!

@skmirajulislam, should I create a new issue to avoid confusion or would it be better to assign this one to me?

**Comment by VaibhavKatariya** [comment]
@skmirajulislam kindly review PR #92

**Comment by skmirajulislam** [comment]
Please note that @Sameeratweb  has also been assigned to this task. I would like to review both of your solutions, and the best one will be selected for merging. Until then, you both can continue working on the issue. After the final solution is selected, the winner will be awarded 3 points under Hacktoberfest and GSSOC.

**Comment by skmirajulislam** [comment]
@VaibhavKatariya solved this issue!
