### ISSUE TITLE
FIX UI OF LOGIN & SIGNUP 

### ISSUE THREAD

**Issue by skmirajulislam** [Vin205/Enyanjyoti#96]
![Screenshot 2024-10-06 214938](https://github.com/user-attachments/assets/5666d9b5-8347-49cb-87ec-a44309e798da)
![Screenshot 2024-10-06 215023](https://github.com/user-attachments/assets/4eb4ad7c-f1c4-45f1-b950-eca09047831b)

fix this problem, it should lie inside the text input field!

**Comment by AnanteshG** [comment]
I can fix this. Assign it to me

**Comment by MohitGoyal09** [comment]
Pls assign this issue to me.

**Comment by skmirajulislam** [comment]
@MohitGoyal09 assigned!

**Comment by skmirajulislam** [comment]
RESOLVED!
